dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh | bash
notifications:
  slack:
    secure: M+sCiOZZ0Nf5+svHTnQ27AK6iY1zKWgxC6AGLT7k3ij0gNvqB37CIg8WNhtWKTBd+SmmrRcgLAH60H1vyDuutHq9SWjdByYdNGnKnk7FUmpslDdjqheK5ayFzrxoraIiw/yqwccRh9iO/Swmet1fkN7fq0gtp+Lum083s4v273crTVdptgqyOGB8Neiv6ulQwCv5NeWo2GOGmeBxwdbexxqRR6NhD8mjOepxytTt2S1E5szsHz4+C7eGocQigQN2S3ku90/QNNSwtUi41AK0mgZIZUfDlEmAeyI+pHRluaWB+tFvxasACgi2SP59VLOsP+9TigB0P5BCbnrN1Wd3kp+P0AtyHSp7sf6/M8YtKK7AaifW/4UXNsa0ovpPr7YjWyq5b9LCCh8P8DSgdCRt9KrmmPPlmaztesOjSOvO8fhwGPxfqe5Z+lXr7+5CSOhQpeHZyb93sf2TFKsOk2ZI6Ej1VFuHAckqjzIxeR/PlwMmW2k9uhngaAptzE30j/Qd+4m5aSqESEA0Jy0oA+bNj3PvVgNLZXfMVhanDguyY0uVulLPo4wSs5sCokvOOnq4THnZHbfeIWqC3CtO+Q9zEPVPBaZ5m1u69ccfVd6qyC6q9utXA1u06tYk9qyIo8EyZxcSQooAFVAFnGvSRMwQ7XVvX+BNrg4kf5+6TmYoMUQ=
